version = 3.11.0
runner.dialect = scala3

rewrite.rules = [
  AvoidInfix,
  RedundantBraces,
  RedundantParens,
  AsciiSortImports,
  SortModifiers,
  PreferCurlyFors
]

align.preset = more
maxColumn = 120