package io.parapet

import java.util.UUID

/** A stable, opaque address used by the parapet runtime to deliver [[Event]]s to a specific
  * [[io.parapet.core.Process]].
  *
  * `ProcessRef` is the only handle a sender needs in order to communicate with a process - the underlying mailbox,
  * scheduler, and process implementation are all hidden behind it. References are value-based: two refs with the same
  * `value` route to the same process.
  *
  * Refs are normally created by the runtime when a process is registered, but user code can mint custom refs (for
  * example, well-known service endpoints) by constructing them directly. Application code should generally treat the
  * inner [[value]] as opaque.
  *
  * @param value
  *   globally unique identifier (typically a UUID, or a well-known string for built-in system processes - see the
  *   companion constants).
  */
final case class ProcessRef(private[parapet] val value: String):
  override def toString: String = value

/** Factory and well-known [[ProcessRef]] constants reserved by the parapet runtime. */
object ProcessRef:
  /** Prefix used by all built-in references to keep the runtime namespace distinct from application-defined refs.
    */
  val ParapetPrefix = "parapet"

  /** Reference to the runtime's [[io.parapet.core.processes.SystemProcess]], which routes lifecycle and failure events.
    */
  val SystemRef: ProcessRef = ProcessRef(s"$ParapetPrefix-system")

  /** Reference to the dead-letter sink. Events sent here are surfaced via the configured
    * [[io.parapet.core.processes.DeadLetterProcess]].
    */
  val DeadLetterRef: ProcessRef = ProcessRef(s"$ParapetPrefix-deadletter")

  /** Reference to the [[io.parapet.core.Scheduler]] itself, used internally for control messages such as `Stop`.
    */
  val SchedulerRef: ProcessRef = ProcessRef(s"$ParapetPrefix-scheduler")

  /** Sentinel reference indicating "no sender". Used as a default for events generated by the runtime that have no
    * originating process.
    */
  val UndefinedRef: ProcessRef = ProcessRef(s"$ParapetPrefix-undefined")

  /** Reference to the no-op process which silently swallows any events sent to it. */
  val NoopRef: ProcessRef = ProcessRef(s"$ParapetPrefix-noop")

  /** Allocates a fresh, globally unique reference backed by a JDK [[UUID]]. */
  def apply(): ProcessRef =
    jdkUUIDRef

  /** Allocates a fresh reference whose [[value]] is a JDK-generated UUID. Functionally identical to [[apply]] - kept as
    * a separate factory so callers can disambiguate intent in code.
    */
  def jdkUUIDRef: ProcessRef =
    new ProcessRef(UUID.randomUUID().toString)
